# Lemon makefile
# $Amigan: fakedbfs/buildtools/Makefile,v 1.1 2005/08/10 00:13:42 dcp1990 Exp $
include ../globals.mk
all: lemon

lemon: lemon.c
	$(CC) -o lemon lemon.c

clean:
	rm -f *.o *.core *~ lemon
