.\" El manpage-o for the specfile format
.\" (C)2005, Dan Ponte
.\" $Amigan: fakedbfs/doc/libfakedbfs.3,v 1.2 2006/01/29 21:07:12 dcp1990 Exp $
.Dd January 29, 2006
.Dt LIBFAKEDBFS 3
.Os
.Sh NAME
.Nm libfakedbfs
.Nd the main library of the Fake Database Filesystem
.Sh SYNOPSIS
.Pp
#include <fakedbfs/fakedbfs.h>
.Pp
#include <fakedbfs/fakedbfsapps.h>
.Pp
fdbfs_t* fdbfs_new(char *dbfile, char **error, void (*debugf)(char *,
enum ErrorAction), int useplugins);
.Pp
int fdbfs_destroy(fdbfs_t *f);
.Sh DESCRIPTION
.Nm
is the main library used by the
.Em fakedbfs
distribution. The main utilities,
.Xr fcreatedb 1 ,
.Xr findex 1 ,
and
.Xr fquery 1
all use it.
.Sh API FUNCTIONS
The main functions that most apps will use include:
.Bl -tag
.It Xr parse_definition 3
.It Xr start_db 3
.El
.Sh SEE ALSO
.Xr libfakedbfs 3 ,
.Xr fcreatedb 5 , 
.Xr findex 1 ,
.Xr fedit 1 ,
.Xr fquery 1
.Sh AUTHOR
Dan Ponte <dcp1990@neptune.atopia.net>
.Pp
Web: http://www.theamigan.net/fakedbfs/
