.\" El manpage-o for findex
.\" (C)2005, Dan Ponte
.\" $Amigan: fakedbfs/fquery/fquery.1,v 1.4 2006/03/06 05:10:18 dcp1990 Exp $
.Dd September 19, 2005
.Dt FQUERY 1
.Os
.Sh NAME
.Nm fquery
.Nd query the fakedbfs database
.Sh SYNOPSIS
.Nm
.Op Fl hvfn
.Op Fl d Ar dbfile
.Ar query_string
.Sh DESCRIPTION
.Nm
is part of the
.Em fakedbfs
distribution. It is used to query the database for files.
.Pp
.Nm
accepts one mandatory argument,
.Ar query_string .
This is a single string, usually quoted using single-quotes in the shell.
See
.Xr fdbfsquery_fmt 7
for more information on the format of queries.
.Pp
One can also use the
.Fl d
flag with the
.Ar dbfile
argument to specify the database to use; by default it is either the value of
the FAKEDBFSDB environment variable, or $HOME/.fakedbfsdb. This convention is
followed by all utilities in this distribution, and should be followed for other
applications using the libfakedbfs library. Note that this database must have already
been created with
.Xr fcreatedb 1 .
It should also have files catalogued in it for maximum utility.
.Pp
.Nm
recognizes the following command line options:
.Bl -tag -width indent
.It Fl f
Print a full listing, including every field, as opposed to just the filenames.
.It Fl h
Print a short usage message.
.It Fl n
Separate output by ASCII NUL characters rather than newlines, for use with the
.Fl 0
argument to
.Xr xargs 1 .
It is similar to
.Xr find 1 's
.Fl print0
option. No effect when
.Fl f
is specified.
.It Fl v
Print the library version, the
.Nm
utility version, and other information.
.It Fl d Ar dbfile
Use
.Ar dbfile
as the database instead of the default.
.El
.Sh DIAGNOSTICS
The
.Nm
utility will print whatever error messages it gets from the library to
.Em stderr .
These usually will include a recursing list of errors as each function returns;
see
.Xr libfakedbfs 3
for more information.
.Sh ENVIRONMENT
The FAKEDBFSDB is the only environment variable that
.Nm
uses. See above for use information.
.Sh FILES
.Bl -tag -width fdbfs
.It Pa ~/.fakedbfsdb
default database file
.El
.Sh SEE ALSO
.Xr libfakedbfs 3 ,
.Xr fcreatedb 1 ,
.Xr fedit 1 ,
.Xr findex 1 ,
.Xr fdbfsquery_fmt 7
.Sh HISTORY
The
.Nm
utility appeared in fakedbfs v1.0.
.Sh BUGS
None. Period. And there never will be. If you think you've found one, it's only
an illusion.
.Sh AUTHOR
Dan Ponte <dcp1990@neptune.atopia.net>
.Pp
Web: http://www.theamigan.net/fakedbfs/
