.\" El manpage-o for fcreatedb
.\" (C)2005, Dan Ponte
.\" $Amigan: fakedbfs/fcreatedb/fcreatedb.1,v 1.1 2005/08/14 02:51:37 dcp1990 Exp $
.Dd August 13, 2005
.Dt FCREATEDB 1
.Os
.Sh NAME
.Nm fcreatedb
.Nd initialise/append to fakedbfs databases from specfiles
.Sh SYNOPSIS
.Nm
.Op Fl hva
.Op Fl d Ar dbfile
.Ar specfile
.Sh DESCRIPTION
.Nm
is part of the
.Em fakedbfs
distribution. It is used to prepare databases for use by the various other
utilities in the distribution.
.Pp
.Nm
accepts one mandatory argument,
.Ar specfile .
This file's format is that of
.Xr specfile 5 .
It specifies the various catalogue fields and enum declarations of the database.
.Pp
One can also use the
.Ar d
argument to specify the database to use; by default it is either the value of
the FAKEDBFSDB environment variable, or $HOME/.fakedbfsdb. This convention is
followed by all utilities in this distribution, and should be followed for other
applications using the libfakedbfs library.
.Pp
.Nm
recognizes the following command line options:
.Bl -tag -width indent
.It Fl h
Print a short usage message.
.It Fl a
Put
.Nm
in
.Dq append
mode. This means that
.Nm
won't even attempt to create the database and set up the default tables (which
is the default). This option is quite useless, as it already checks if the
database is initialised before attempting anyway. It is provided primarily for
debugging purposes.
.It Fl v
Print the library version, the
.Nm
utility version, and other information.
.It Fl d Ar dbfile
Use
.Ar dbfile
as the database instead of the default.
.Sh DIAGNOSTICS
The
.Nm
utility will print whatever error messages it gets from the library to
.Em stderr .
These usually will include a recursing list of errors as each function returns;
see
.Xr libfakedbfs 3
for more information.
.Sh ENVIRONMENT
The FAKEDBFSDB is the only environment variable that
.Nm
uses. See above for use information.
.Sh FILES
.Bl -tag -width fdbfs
.It Pa ~/.fakedbfsdb
default database file
.Sh SEE ALSO
.Xr libfakedbfs 3 ,
.Xr specfile 5 ,
.Xr findex 1 ,
.Xr fedit 1 ,
.Xr fquery 1
.Sh HISTORY
The
.Nm
utility appeared in fakedbfs v1.0.
.Sh BUGS
.Nm
should be merged into
.Xr fedit 1 ,
but the author is too lazy.
.Sh AUTHOR
Dan Ponte <dcp1990@neptune.atopia.net>
.Pp
Web: http://www.theamigan.net/fakedbfs/
